import SwiftUI

/// Shows cross references for a verse. References (and one-line reasons) are
/// generated by Claude, then each is hydrated with its actual ESV text.
struct CrossReferenceSheet: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(\.colorScheme) private var scheme
    @EnvironmentObject private var settings: SettingsStore

    let verse: Verse

    @State private var references: [CrossReferenceService.CrossReference] = []
    @State private var isLoading = true
    @State private var errorMessage: String?

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: Theme.Space.m) {
                    Card {
                        VStack(alignment: .leading, spacing: Theme.Space.xs) {
                            Pill(text: verse.displayReference, tint: settings.accent.color)
                            Text(verse.text)
                                .font(.custom("Georgia", size: 16))
                                .foregroundStyle(Theme.primaryText(scheme))
                        }
                    }

                    if isLoading {
                        VStack(spacing: Theme.Space.s) {
                            ProgressView()
                            Text("Finding connections across Scripture\u{2026}")
                                .font(.system(size: 13))
                                .foregroundStyle(Theme.secondaryText(scheme))
                        }
                        .frame(maxWidth: .infinity)
                        .padding(Theme.Space.l)
                    } else if let errorMessage {
                        ErrorBanner(message: errorMessage, onDismiss: nil)
                    } else if references.isEmpty {
                        EmptyStateView(systemImage: "arrow.triangle.branch",
                                       title: "No cross references",
                                       message: "Claude didn't return any references for this verse.")
                    } else {
                        ForEach(references) { ref in
                            referenceCard(ref)
                        }
                    }
                }
                .padding(Theme.Space.l)
            }
            .navigationTitle("Cross References")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) { Button("Done") { dismiss() } }
            }
            .task { await load() }
        }
    }

    private func referenceCard(_ ref: CrossReferenceService.CrossReference) -> some View {
        Card {
            VStack(alignment: .leading, spacing: Theme.Space.s) {
                Text(ref.reference)
                    .font(.system(size: 16, weight: .semibold))
                    .foregroundStyle(settings.accent.color)
                if let text = ref.text {
                    Text(text)
                        .font(.custom("Georgia", size: 15))
                        .foregroundStyle(Theme.primaryText(scheme))
                }
                Text(ref.reason)
                    .font(.system(size: 13))
                    .foregroundStyle(Theme.secondaryText(scheme))
            }
        }
    }

    private func load() async {
        guard settings.hasClaudeKey else {
            errorMessage = "Add your Claude API key in Settings to generate cross references."
            isLoading = false
            return
        }
        guard settings.hasESVKey else {
            errorMessage = "Add your ESV API key in Settings so reference text can be fetched."
            isLoading = false
            return
        }
        isLoading = true
        defer { isLoading = false }
        do {
            references = try await settings.makeCrossReferences().crossReferences(for: verse)
        } catch {
            errorMessage = (error as? LocalizedError)?.errorDescription ?? error.localizedDescription
        }
    }
}
